name: SSASpawnerLimiter
version: '${version}'
main: github.io.ssaspawnerlimiter.SSASpawnerLimiter
api-version: '1.21'
author: Nighter
depend: [SmartSpawner]
folia-supported: true
description: "Addon for SmartSpawner that limits spawner placement per chunk"

permissions:
  ssaspawnerlimiter.bypass:
    description: "Bypass spawner chunk limit"
    default: false

  ssaspawnerlimiter.command.use:
    description: "Base permission for SSASpawnerLimiter commands, must have to use any command"
    default: op

  ssaspawnerlimiter.command.info:
    description: "Check spawner count in current chunk"
    default: true

  ssaspawnerlimiter.command.reload:
    description: "Reload plugin configuration"
    default: op

  ssaspawnerlimiter.command.stats:
    description: "View plugin statistics"
    default: op
