name: SSASpawnerLimiter
version: '${version}'
main: github.io.ssaspawnerlimiter.SSASpawnerLimiter
api-version: '1.21'
author: Nighter
depend: [SmartSpawner]
folia-supported: true
description: "Addon for SmartSpawner that limits spawner placement per chunk"

permissions:
  ssaspawnerlimiter.bypass:
    description: "Bypass spawner chunk limit"
    default: false

  ssaspawnerlimiter.perplayer.bypass:
    description: "Bypass per-player spawner limit (unlimited spawners)"
    default: false

  ssaspawnerlimiter.command.use:
    description: "Base permission for SSASpawnerLimiter commands, must have to use any command"
    default: op

  ssaspawnerlimiter.command.check:
    description: "Check spawner limit for a specific player's chunk"
    default: op

  ssaspawnerlimiter.command.checkplayer:
    description: "Check per-player spawner count"
    default: op

  ssaspawnerlimiter.command.info:
    description: "Check spawner count in current chunk"
    default: op

  ssaspawnerlimiter.command.reload:
    description: "Reload plugin configuration"
    default: op

  ssaspawnerlimiter.command.stats:
    description: "View plugin statistics"
    default: op
